on:
  schedule:
    - cron: '40 10,11,12 * * *'
jobs:
  get_daily_currencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: yarn
      - run: yarn start
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}